### ISSUE TITLE
Wrong result with broadcasted function

### ISSUE THREAD

**Issue by aminya** [triscale-innov/GFlops.jl#10]
```jl
using GFlops

x = rand(10)

@gflops sin.($x)
```
gives 0.0

blocking https://github.com/aminya/AcuteBenchmark.jl/issues/2 and https://github.com/chriselrod/LoopVectorization.jl/issues/5

**Comment by ffevotte** [comment]
Can you confirm that this happens only with Julia 1.4?

If so, it looks suspiciously like issue #6, which is due to some incompatibilities between (the currently released version of) Cassette.jl and Julia v1.4.

In local tests, I can indeed confirm that Cassette's current `master` fixes this issue too, most probably thanks to [this PR](https://github.com/jrevels/Cassette.jl/pull/163).

**Comment by aminya** [comment]
I only tried in Julia 1.4. I don't have an older version to try.
